### ISSUE TITLE
Question about print(mydt_wide)

### ISSUE THREAD

**Issue by qdread** [mweinroth/epi2me2r#1]
In your scripts `amr_raw_to_metagenomeseq.R`, `amr_raw_to_phyloseq.R`, and `read_in_amr_files.R` you have some code like

```
if (keepSNP == TRUE) {
  print(mydt_wide)
} else {
  ... some stuff ...
  mydt_wide
}
```

So the `print()` is used in one condition but not the other. The `print()` seems wrong because you are trying to return the object not print it. I was wondering if that `print` was intentional or not.

**Comment by mweinroth** [comment]
You are correct it's left over from an earlier attempt I will delete them.

**Comment by mweinroth** [comment]
@qdread is it better form to have the last returned dataframe 
as just `dataframe` or `return(dataframe)` we currently have it as both.

**Comment by qdread** [comment]
Well I was reading some interesting discussion on this point. https://stackoverflow.com/questions/11738823/explicitly-calling-return-in-a-function-or-not Apparently people have very strong opinions about it! I think it is probably best to just be consistent and stick with either using it or not. Probably the current trend is to not use it. So probably worth it to go through and either get rid of all returns or add them in where necessary, depending on what your personal preference is :-D

**Comment by mweinroth** [comment]
I got rid of returns (I think) if you see anymore feel free to delete them.
