### ISSUE TITLE
checking input on wimp read in

### ISSUE THREAD

**Issue by mweinroth** [mweinroth/epi2me2r#4]
I was not sure in the script `read_in_wimp_files` what the aim of L16-18 is: 

>   if(!format %in% c('wide', 'long')) {
>     stop('format should be either "wide" or "long"')
>   }

 It is erroring out the function currently so I have it commented out but once it's changed I can retest it.

**Comment by mweinroth** [comment]
@qdread it will not let me assign you

**Comment by qdread** [comment]
Oops, I think I left that in there by mistake. I wrote that and thought I had deleted it. You should delete!

Also you probably need to add me as collaborator on the repo in the settings before you can assign me to tasks.

**Comment by qdread** [comment]
OK I'm invited now! I will still continue to make pull requests instead of directly pushing to the repo, though.

**Comment by qdread** [comment]
Closing this, seems like it's fixed
