### ISSUE TITLE
amra versus arma

### ISSUE THREAD

**Issue by qdread** [mweinroth/epi2me2r#6]
I see that in the amr_raw_to_metagenomeseq.R and amr_raw_to_phyloseq.R, the metadata column names that have to be included are `arma_filename` and `amra_barcode` but it doesn't make sense to me that one of them is `arma` and the other is `amra`. Is that a typo or are they actually spelled differently in the two different columns?

**Comment by mweinroth** [comment]
typo. `arma` is the correct spelling from the epi2me website (`amra` is incorrect and should be replaced) I will go through and change the ones I can find.
